import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Lexend } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { ImGithub } from "react-icons/im"
import { ImLinkedin } from "react-icons/im"
import { ImSphere } from "react-icons/im"

const inter = Inter({ subsets: ['latin'] })
const lexend = Lexend({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Coala</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className={styles.wrapper}>
        <div className={styles.headerWrapper}>
          <header className={styles.description}>    
                <div className={styles.logo}>
                  <Image
                        src="/Logo.svg"
                        alt="Logo"
                        width={70}
                        height={70}
                        priority
                      />  
                  <h1 className={lexend.className}>      
                    Coala
                  </h1>
                </div>
                  <div className={styles.navwrapper}>
                    <nav className={lexend.className}>
                    <a href="#features">Features</a> 
                    <a href="#team">Team</a> 
                    <a href="#prototype">Prototype</a> 
                    <a href="#contact">Contact</a>
                    </nav>
                    <button className={styles.button}>View Proposal</button>
                  </div>
          </header>
           </div>
   
          <main className={styles.main}>
          
          
            <div className={styles.center}>
              <div className={styles.introduction}>
                <h3 className={lexend.className}>Helping Coaches to save time</h3>
                <p className={lexend.className}>Spend more time helping students reach their full potential by focusing on providing quality coaching sessions with powerful and easy to use features!</p>
                <button className={styles.button}>Try Coala</button>
              </div>
              <Image
                className={styles.collage}
                src="/collage.svg"
                alt="collage"
                width={700}
                height={700}
                />
            </div>

            <div className={styles.video}>
            </div>

            <div className={styles.features} id="features">
              <h2 className={lexend.className} >The Features</h2>
              <h5 className={lexend.className}>Introducing our personalized coaching solution! </h5>
              <div className={styles.tab}>
                <div>
                <h4 className={lexend.className}>Smart Curriculum</h4>
                <p className={lexend.className}>A personalized solution tailored for every coach to easily access the details and sample videos about each skill exercise required on a program.</p>
                </div>
                <Image
                className={styles.curriculum}
                src="/Curriculum.svg"
                alt="Curriculum"
                width={400}
                height={400}
                />
                
              </div> 
            </div>


            <div className={styles.team} id="team">
              <h2 className={lexend.className}>The Team</h2>
              <h5 className={lexend.className}>Our amazing team that can make anything possible! </h5>
              <div className={styles.grid}>
                <div     className={styles.card}>
                <Image
                className={styles.profile}
                src="/headshots/danika.png"
                alt="danika"
                width={306}
                height={254}
                />
                 <div className={styles.profileText}>
                  <h4 className={lexend.className}>
                  Danika Enad 
                  </h4>
                  <p className={lexend.className}>
                  Full Stack Developer
                  </p>
                  <a
                  href="https://www.linkedin.com/in/danikaenad"
                  className={styles.linkedin}
                  >
                    <ImLinkedin />
                  </a>
                  
                  <a
                    href="https://github.com/denad00"
                  >
                    <ImGithub />
                  </a>
                  </div>
                </div>

                <div    className={styles.card}>
                <Image
                className={styles.profile}
                src="/headshots/elmer.png"
                alt="elmer"
                width={306}
                height={254}
                />
                 <div className={styles.profileText}>
                  <h4 className={lexend.className}>
                  Elmer Balbin 
                  </h4>
                  <p className={lexend.className}>
                  Full Stack Developer
                  </p>
                  <a
                  href="https://www.linkedin.com/in/elmzarnsi"
                  className={styles.linkedin}
                  >
                    <ImLinkedin />
                  </a>
                  <a
                    href="https://github.com/elmerdotdev"
                  >
                    <ImGithub />
                  </a>
                  </div>
                </div>

                <div  className={styles.card}>
                <Image
                className={styles.profile}
                src="/headshots/iris.png"
                alt="iris"
                width={306}
                height={254}
                />
                 <div className={styles.profileText}>
                  <h4 className={lexend.className}>
                  Iris Chen 
                  </h4>
                  <p className={lexend.className}>
                  Full Stack Developer
                  </p>
                  <a
                  href="https://www.linkedin.com/in/iris-jiamin-chen"
                  className={styles.linkedin}
                  >
                    <ImLinkedin />
                  </a>
                  <a
                    href="https://github.com/jaminitaa"
                  >
                    <ImGithub />
                  </a>
                  </div>
                </div>

                <div className={styles.card}>
                <Image
                className={styles.profile}
                src="/headshots/keiko.png"
                alt="keiko"
                width={306}
                height={254}
                />
                 <div className={styles.profileText}>
                  <h4 className={lexend.className}>
                  Keiko Shimizu 
                  </h4>
                  <p className={lexend.className}>
                  Full Stack Developer
                  </p>
                  <a
                  href="https://www.linkedin.com/in/keikoshimizu"
                  className={styles.linkedin}
                  >
                    <ImLinkedin />
                  </a>
                  <a
                    href="https://github.com/keikoshimizu"
                  >
                    <ImGithub />
                  </a>
                  </div>
                </div>

                <div  className={styles.card}>
                <Image
                className={styles.profile}
                src="/headshots/giancarlo.png"
                alt="giancarlo"
                width={306}
                height={254}
                />
                  <div className={styles.profileText}>
                  <h4 className={lexend.className}>
                  Giancarlo Cochella
                  </h4>
                  <p className={lexend.className}>
                  UI/UX Designer
                  </p>
                  <a
                  href="https://www.linkedin.com/in/giancarlocochella"
                  className={styles.linkedin}
                  >
                    <ImLinkedin />
                  </a>
                  <a
                    href="https://www.giancochella.com"
                  >
                    <ImSphere />
                  </a>
                  </div>
                </div>

                <div  className={styles.card}>
                <Image
                className={styles.profile}
                src="/headshots/herlan.png"
                alt="herlan"
                width={306}
                height={254}
                />
                  <div className={styles.profileText}>
                  <h4 className={lexend.className}>
                  Herlan Wijaya
                  </h4>
                  <p className={lexend.className}>
                  Product Designer
                  </p>
                  <a
                  href="https://www.linkedin.com/in/herlanwijaya"
                  className={styles.linkedin}
                  >
                    <ImLinkedin />
                  </a>
                  <a
                    href="https://www.herlanwijaya.com"
                  >
                    <ImSphere />
                  </a>
                  </div>
                </div>

                <div  className={styles.card}>
                <Image
                className={styles.profile}
                src="/headshots/jane.jpg"
                alt="jane"
                width={306}
                height={254}
                />
                  <div className={styles.profileText}>
                  <h4 className={lexend.className}>
                  Jane (Jeongeun) Choi
                  </h4>
                  <p className={lexend.className}>
                  UI/UX Designer
                  </p>
                  <a
                  href="https://www.linkedin.com/in/janechoi92"
                  className={styles.linkedin}
                  >
                    <ImLinkedin />
                  </a>
                  <a
                    href="https://www.janefolio.com"
                   
                  >
                    <ImSphere />
                  </a>
                  </div>
                </div>

                <div className={styles.card}>
                <Image
                className={styles.profile}
                src="/headshots/joanne.png"
                alt="jane"
                width={306}
                height={254}
                />
                  <div className={styles.profileText}>
                  <h4 className={lexend.className}>
                  Joanne (Kyungeun) Cho
                  </h4>
                  <p className={lexend.className}>
                  UI/UX Designer
                  </p>
                  <a
                  href="https://www.linkedin.com/in/joanne-k-cho"
                  className={styles.linkedin}
                  >
                    <ImLinkedin />
                  </a>
                  <a
                    href="https://www.joannekcho.com"
               
                  >
                    <ImSphere />
                  </a>
                  </div>
                </div>

                <div  className={styles.card}>
                <Image
                className={styles.profile}
                src="/headshots/yuenki.png"
                alt="jane"
                width={306}
                height={254}
                />
                <div className={styles.profileText}>
                  <h4 className={lexend.className}>
                  Yuen Ki Hung
                  </h4>
                  <p className={lexend.className}>
                  UI/UX Designer
                  </p>
                  <a
                  href="https://www.linkedin.com/in/yuenki-hung"
                  className={styles.linkedin}
                  >
                    <ImLinkedin />
                  </a>
                  <a
                    href="https://www.yk-hung.com"
           
                  >
                    <ImSphere />
                  </a>
                  </div>
                </div>

                
              </div>
            </div>

            <div className={styles.cta} id="prototpe">
              <h2 className={lexend.className}>Give Coala a Try!</h2>
              <div className={lexend.className}>Figma Prototype</div>
            </div>
          </main>
          <footer className={styles.contact} id="contact">
            <div className={styles.contactForm}>
              <h2 className={lexend.className}>Get In Touch!</h2>
              <div className={styles.form}>
                <form className={lexend.className}>
                <input className={lexend.className} type="text" id="name" name="name" value="Name"></input>
                <input className={lexend.className} type="text" id="telephone" name="lname" value="Telephone"></input>
                <input className={lexend.className} type="text" id="email" name="email" value="Email"></input>
                <input className={lexend.className} type="text" id="comment" name="comment" value="Comment"></input>
                <input className={lexend.className} type="submit" value="Submit"></input>
                </form>
              </div>
            </div>
              <div className={styles.slogan}>
                <Image
                    src="/Logo.svg"
                    alt="Logo"
                    className={styles.vercelLogo}
                    width={50}
                    height={50}
                    priority
                  />
                <p className={lexend.className}>Boost your coaching efficiency</p>
                <p className={lexend.className}>anywhere, anytime!</p>
              </div>
            </footer>
        </div>
    </>
  )
}
